export const GET_ROLES_REQUEST = 'GET_ROLES_REQUEST';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';

export const DELETE_ROLE_REQUEST = 'DELETE_ROLE_REQUEST';
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
export const DELETE_ROLE_FAILURE = 'DELETE_ROLE_FAILURE';

export const EDIT_ROLE_REQUEST = 'EDIT_ROLE_REQUEST';
export const EDIT_ROLE_SUCCESS = 'EDIT_ROLE_SUCCESS';
export const EDIT_ROLE_FAILURE = 'EDIT_ROLE_FAILURE';

export const TOGGLE_ROLE_PERMISSION_REQUEST = 'TOGGLE_ROLE_PERMISSION_REQUEST';
export const TOGGLE_ROLE_PERMISSION_SUCCESS = 'TOGGLE_ROLE_PERMISSION_SUCCESS';
export const TOGGLE_ROLE_PERMISSION_FAILURE = 'TOGGLE_ROLE_PERMISSION_FAILURE';

export const FIND_ROLE_BY_ID_REQUEST = 'FIND_ROLE_BY_ID_REQUEST';
export const FIND_ROLE_BY_ID_SUCCESS = 'FIND_ROLE_BY_ID_SUCCESS';
export const FIND_ROLE_BY_ID_FAILURE = 'FIND_ROLE_BY_ID_FAILURE';
